# Source: plex/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: v1.28.0.5999-97678ded3
    helm.sh/chart: plex-6.4.3
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: plex/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-media
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: v1.28.0.5999-97678ded3
    helm.sh/chart: plex-6.4.3
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
# # Source: plex/templates/common.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: plex
#   labels:
#     app.kubernetes.io/instance: plex
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: plex
#     app.kubernetes.io/version: v1.28.0.5999-97678ded3
#     helm.sh/chart: plex-6.4.3
#   annotations:
# spec:
#   type: ClusterIP
#   ports:
#   - port: 32400
#     targetPort: http
#     protocol: TCP
#     name: http
#   selector:
#     app.kubernetes.io/name: plex
#     app.kubernetes.io/instance: plex
---
# Source: plex/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: v1.28.0.5999-97678ded3
    helm.sh/chart: plex-6.4.3
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app.kubernetes.io/instance: plex
    spec:
      hostNetwork: true      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: plex
          image: "ghcr.io/k8s-at-home/plex:v1.28.0.5999-97678ded3"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
            - name: dlna-tcp
              containerPort: 32469
              protocol: TCP
            - name: dlna-udp
              containerPort: 1900
              protocol: UDP
            - name: plex-companion
              containerPort: 3005
              protocol: TCP
            - name: discovery-udp
              containerPort: 5353
              protocol: UDP
            - name: plex-roku
              containerPort: 8324
              protocol: TCP
            - name: gdm-32410
              containerPort: 32410
              protocol: UDP
            - name: gdm-32412
              containerPort: 32412
              protocol: UDP
            - name: gdm-32413
              containerPort: 32413
              protocol: UDP
            - name: gdm-32414
              containerPort: 32414
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data-volume
              mountPath: /media
            - name: nasmedia
              mountPath: /nasmedia              
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
        - name: data-volume
          hostPath:
            path: /media
            type: ''
        - name: nasmedia
          hostPath:
            path: /nasmedia
            type: ''            
---
# # Source: plex/templates/common.yaml
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: plex
#   labels:
#     app.kubernetes.io/instance: plex
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: plex
#     app.kubernetes.io/version: v1.28.0.5999-97678ded3
#     helm.sh/chart: plex-6.4.3
# spec:
#   rules:
#     - host: "192.168.1.96"
#       http:
#         paths:
#           - path: "/"
#             pathType: Prefix
#             backend:
#               service:
#                 name: plex
#                 port:
#                   number: 32400
