kind: Namespace
apiVersion: v1
metadata:
  name: podinfo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: podinfo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      labels:
        app: podinfo2
      annotations:
        prometheus.io/port: '9797'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:6.2.0
          command:
            - ./podinfo
            - '--port=9898'
            - '--port-metrics=9797'
            - '--grpc-port=9999'
            - '--grpc-service-name=podinfo'
            - '--level=info'
            - '--random-delay=false'
            - '--random-error=false'
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc
              containerPort: 9999
              protocol: TCP
          env:
            - name: PODINFO_UI_COLOR
              value: '#34577c'
          resources:
            limits:
              cpu: '2'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
