apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: nginx-ingress
spec:
  cidrs:
    - cidr: "192.168.1.96/24"
  disabled: false
  # serviceSelector:
  #   matchLabels:
  #     app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: ext-svc-ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    "io.cilium/lb-ipam-ips": "192.168.1.96"
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies: 
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443-tcp
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller