apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: guestbook
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps/
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
